listen = true
show_changes_count = true
on_change_strategy = "kill_then_restart"

[exports.locations]
auto = false
exporter = "locations"
path = ".bacon-locations"
line_format = "{item-idx}: {kind} {path}:{line}:{column} {message}"

[keybindings]
ctrl-r = "rerun"
esc = "back"
g = "scroll-to-top"
shift-g = "scroll-to-bottom"
k = "scroll-lines(-1)"
j = "scroll-lines(1)"
ctrl-u = "scroll-page(-1)"
ctrl-d = "scroll-page(1)"
n = "next-match"
shift-n = "previous-match"
