[alias]
rr = "run --release"

[build]
rustc-wrapper = "/usr/sbin/sccache"

[target.'cfg(target_os = "linux")']
linker = "clang" 
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "-C", "link-arg=-flto", "-C", "linker-plugin-lto"]

[profile.release]
#lto = "fat"

[profile.dev]
debug = "line-tables-only"

[profile.dev.package."*"]
debug = false

[profile.debugging]
inherits = "dev"
debug = true
