general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    inhibit_sleep = 1
}

listener {
    timeout = 100
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

listener {
    timeout = 120
    on-timeout = loginctl lock-session ; hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

