general {
    ignore_empty_input = true
}

auth {
    fingerprint {
        enabled = true
        ready_message = or scan fingerprint...
        present_message = scanning fingerprint...
    }
}

background {
    monitor =
    path = ~/Pictures/wallpapers/purple_bg.png
    color = rgb(000000)
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    dots_rounding = -1
    outer_color = rgba(CC0A9F00)
    inner_color = rgba(24262B66)
    font_color = rgb(CCCCFF)
    font_family = 0xProto Nerd Font
    fade_on_empty = false
    fade_timeout = 1000
    placeholder_text = <i>Input Password...</i>
    hide_input = false
    rounding = -1
    check_color = rgb(20413634)
    fail_color = rgb(2043434)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> 
    fail_timeout = 2000
    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false

    position = 0, -170
    halign = center
    valign = center
}

label {
    monitor =
    text = Hi $USER~
    text_align = center
    color = rgb(CCCCFF)
    font_size = 50
    font_family = 0xProto Nerd Font
    rotate = 0

    position = 0, 50
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] ~/.scripts/hyprlock/time.sh
    text_align = center
    color = rgb(CCCCFF)
    font_size = 25
    font_family = 0xProto Nerd Font
    rotate = 0

    position = 0, -60
    halign = center
    valign = center
}

label {
    monitor =
    text = $FPRINTPROMPT
    text_align = center
    color = rgb(CCCCFF)
    font_size = 15
    font_family = 0xProto Nerd Font
    rotate = 0

    position = 0, -230
    halign = center
    valign = center
}



label {
    monitor =
    text = cmd[update:10000] echo " $(uname -sr)"
    text_align = center
    color = rgb(CCCCFF)
    font_size = 25
    font_family = 0xProto Nerd Font
    rotate = 0

    position = 0, 10
    halign = center
    valign = bottom
}

label {
    monitor =
    text = cmd[update:10000] echo "$(LC_TIME=en_US.UTF-8 date +"󰃭  %a, %d.%m.%Y")"
    text_align = center
    color = rgb(CCCCFF)
    font_size = 25
    fant_family = 0xProto Nerd Font
    rotate = 0

    position = -10, 10
    halign = right
    valign = bottom
}

label {
    monitor =
    text = cmd[update:1000] ~/.scripts/hyprlock/media.sh


    text_align = center
    color = rgb(CCCCFF)
    font_size = 25
    font_family = 0xProto Nerd Font
    rotate = 0

    position = 10, 10
    halign = left
    valign = bottom
}

label {
    monitor =
    text = cmd[update:1000] ~/.scripts/hyprlock/battery.sh

    text_align = center
    color = rgb(CCCCFF)
    font_size = 25
    font_family = 0xProto Nerd Font
    rotate = 0

    position = -10, -10
    halign = right
    valign = top
}
